### ISSUE TITLE
previous(#) and next(#) broken

### ISSUE THREAD

**Issue by mmraz** [singingfish/p5-array-circular#2]
Calling $a->previous(7) produces the error:

> Can't locate object method "previous" via package "6" (perhaps you forgot to load "6"?) at /Library/Perl/5.18/Array/Circular.pm line 70.

$num->previous should be $self-previous

I modified my local copy and it behaves as expected.  I will try to submit a PR for this issue.

**Comment by mmraz** [comment]
Same issue for $a->next(2) produces a similar error:
> Can't locate object method "next" via package "1" (perhaps you forgot to load "1"?) at /Library/Perl/5.18/Array/Circular.pm line 51.

$num->next should be $self->next

**Comment by dr-kd** [comment]
If you cant do a  PR, a failing test would be ace.

**Comment by dr-kd** [comment]
thanks for this, fixed in 0d9b20677 & released to the cpan as v 0.003
